infobloxopen/infoblox-ansible

library/infoblox_network.py

Would require: https://github.com/infobloxopen/infoblox-client/pull/170 to be pushed to work for comments

First module add

---

ansible_collections/infoblox/nios_modules/plugins/modules/nios_fixed_address.py

Fixed errors in file nios_host_record.py
Please review the PR @Vaishnavi-infoblox

Fixed doc-missing-type: Argument and parameter-type-not-in-doc: Argument errors

---

ansible_collections/infoblox/nios_modules/plugins/modules/nios_host_record.py

Fixed  the following errors:
doc-missing-type: Argument
parameter-type-not-in-doc: Argument 
undocumented-parameter: Argument errors
@Vaishnavi-infoblox Please review the PR

Fixed errors of nios_host_record

---

ansible_collections/infoblox/nios_modules/plugins/module_utils/api.py
ansible_collections/infoblox/nios_modules/plugins/modules/nios_dtc_lbdn.py
ansible_collections/infoblox/nios_modules/plugins/modules/nios_dtc_pool.py
ansible_collections/infoblox/nios_modules/plugins/modules/nios_dtc_server.py
ansible_collections/infoblox/nios_modules/plugins/modules/nios_restartservices.py
ansible_collections/infoblox/nios_modules/tests/sanity/ignore-2.10.txt
ansible_collections/infoblox/nios_modules/tests/sanity/ignore-2.11.txt

This PR adds support to manipulate DTC(*) objects.
I have not implemented every single option and operation that the API permits, but this is the minimum necessary to have a GSLB.
Each module's documentation contain examples.
I am still working to implement more objects and options, but I would like to start the code review right away, and slowly work on adding the other things later.
* DTC = Infoblox DNS Traffic Control, i.e. GSLB (Global Service Load Balancing).

Add modules to manipulate DTC objects

---

ansible_collections/infoblox/nios_modules/plugins/module_utils/api.py

I sent [this same PR](https://github.com/ansible-collections/community.general/pull/1470/) to `community.general` collection and the maintainers asked me to also send it to this repo
This fix allows to remove aliases from host objects using module `nios_host_record`. All the details are in https://github.com/ansible-collections/community.general/issues/1335
As I am not familiar with the nios modules and `nios_modules/plugins/module_utils/api.py` is used by many other modules I tried that this PR only affects the use case I tested. That's why I use `if key == 'aliases'` . I verified that that there is no other nios module using an argument named `aliases` so I think this fix should only apply for the use case I tried to fix. Let me know if you know of a better approach to fix the bug

fix to be able to remove aliases with module nios_host_record

---

ansible_collections/infoblox/nios_modules/plugins/lookup/nios_next_ip.py

SUMMARY
Current module only works with ipv4. I am adding patch to support ipv6 as well.
ISSUE TYPE
Feature Pull Request
COMPONENT NAME
nios_next_ip
ADDITIONAL INFORMATION
Before my changes:
PLAY [localhost] ***************************************************************************************************************************************************************************************************
TASK [Find next available IP in Infoblox when host does not exist and IP is not defined] ***************************************************************************************************************************
No handlers could be found for logger "infoblox_client.connector"
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin …

adding support for ipv6

---

plugins/modules/nios_dtc_server.py

As per https://ipam.illinois.edu/wapidoc/objects/dtc.server.html API supports disable option. This patch is just exposing it to ansible.

Expanding for disable value

---

plugins/modules/nios_fixed_address.py

Hi,
I just wanted to improve the docs section of nios_fixed_address module. At present it is not clear how to add a reservation in ifoblox using ansible. The nios_fixed_address module allows to do that if mac address is specified as mac: 00:00:00:00:00:00.
This is documented in "Infoblox Deployment Guide - Infoblox REST API - February 2022 that is available here: https://www.infoblox.com/wp-content/uploads/infoblox-deployment-infoblox-rest-api.pdf on page 67 (at the bottom).
Cheers,
Robert

Added documentation for a fixed address reservation

---

plugins/modules/nios_network.py

Added lines for deleting template

NIOSSPT Resolving network deletion in the networks

---

.github/workflows/ansible-test.yml
plugins/module_utils/api.py
plugins/modules/nios_network.py

Added object ref for template feature

NIOSSPT Ansible cannot delete the network

---

.github/workflows/ansible-test.yml
plugins/doc_fragments/nios.py
plugins/module_utils/api.py
tests/unit/plugins/module_utils/test_api.py

With changes to add certificate and key feature to extra layer security

Added certificate authentication feature

---

changelogs/changelog.yaml

This line is breaking the Ansible porting guide CI. It is seeing the first * and assuming this is a bold syntax and the ending * is missing.  Adding backticks around this so the ansible/ansible CI understands the sentence.
This PR is required for Ansible 7 and will thus mean I think that this collection needs to spin a new release as soon as possible.

Fix the 1.4.0 major changes changelog

---

plugins/lookup/nios_next_ip.py
plugins/lookup/nios_next_network.py

Since there can be multiple network views containing the same networks, we need to ensure that the correct network in the `network_obj` list is picked based on a network view name, instead of simply taking it from the first one in the list. The 'default' view is used by default.
Fixes: #156

Enforce selecting ref from network_obj based on network view

---

changelogs/changelog.yaml
plugins/lookup/nios_next_ip.py
plugins/lookup/nios_next_network.py
plugins/modules/nios_nsgroup.py
tests/unit/requirements.txt

This fix contains changes in changelogs.yaml and with lookup modules containing nios_next_ip.py and nios_next_network.py for returning ansible error as no records found if ref list is empty in both modules

Fix to changelog and lookup modules

---

plugins/module_utils/api.py

Previously nios_network_view was failing to update the network_view new_name with camelCase from old_name with lowercase. And nios_a_record is having issue with dynamically add a record with next available ip, this fix will work till infoblox-client version 0.5.0 but this change fails for the above versions

Fix for nios_a_record and nios_network_view

---

plugins/module_utils/api.py

This fix contains both updating A Record with dynamic ip allocation, for Update and Create. 
And also update ip statically for A record

Fixes dynamic and static ip updation for a record

---

plugins/lookup/nios_next_ip.py

This parameter add use_range parameter to nios_next_ip lookup plugin. With this parameter set to true, the plugin will return first available IP from the network range, assigned to the network.
Fixes: https://github.com/infobloxopen/infoblox-ansible/issues/199

Add use_range parameter to nios_next_ip

---

plugins/lookup/nios_next_ip.py

- Added support for IPv6 next available IPs in network ranges.

Added support for IPv6 next available IPs in network ranges.

---

.github/workflows/ansible-test.yml
plugins/doc_fragments/nios.py
plugins/lookup/nios_next_ip.py
plugins/module_utils/api.py
plugins/modules/nios_network.py
tests/integration/targets/nios_network/tasks/nios_network_idempotence.yml
tests/unit/plugins/modules/test_nios_network.py

[IMP] added support for use_logic_filter_rules
[UPD] added use_logic_filter_rules in example.
[IMP] added unit test cases for logic_filter_rules
- added use_logic_filter_rules and logic_filter_rules documentation.
- corrected sanity test failures.
**Sanity Test Result:**
```
Execute command: /root/.ansible/test/venv/sanity.yamllint/3.10/61ebfb13/bin/python /tmp/ansible-test-alczji_m-pip.py uninstall -y --disable-pip-version-check pip wheel
Run command: /root/.ansible/test/venv/sanity.yamllint/3.10/61ebfb13/bin/python /root/ansible/test/lib/ansible_test/_util/target/tools/yamlcheck.py
Run command with data: /root/.ansible/test/venv/sanity.yamllint/3.10/61ebfb13/bin/python /root/ansible/test/lib/ansible_test/_util/controller/sanity/yamllint/yamllinter.py
WARNING: There following sanity test …
```

Pull 196: added support for use_logic_filter_rules and sanity fixes.

---

plugins/module_utils/api.py

[FIX] added check for list element match.

[FIX] added check for list element match.

---

plugins/module_utils/api.py
plugins/modules/nios_range.py

- Fixed [NPA-113] Unable to remove DHCP options from DHCP Range using ansible.

- [NPA-113] Unable to remove DHCP options from DHCP Range using ansible.

---

changelogs/fragments/229-handle-host-rename-without-dns.yml
plugins/module_utils/api.py

This logic was already applied to scenarios that were not updating a name (lines 715-719). This commit simply applies the same logic to scenarios where names are being updated. Without this change, attempts to update the name of an existing host record that was created with `configure_for_dns: false` fail to find the existing record.

 Exclude DNS View from filter criteria when configure_for_dns is false

---

plugins/module_utils/api.py

- [NPA-125] unable to configure dhcp options with combination of 'num' and 'name' field.

[NPA-125] unable to configure dhcp options with combination of 'num' and 'name' field.

---

plugins/module_utils/api.py
plugins/modules/nios_host_record.py

[FIX] NPA-173: Fix host record PXE server with alias naming
[FIX] NPA-174: FIX re-run of HOST Record with MAC
[FIX] NPA-167: Fix re-run of Host Record with nextserver

Fix Bugs on Host Record

---

.github/workflows/ansible-test.yml
README.md
plugins/module_utils/api.py
plugins/modules/nios_adminuser.py
plugins/modules/nios_network.py
plugins/modules/nios_vlan.py
tests/integration/targets/nios_adminuser/tasks/nios_adminuser_idempotence.yml
tests/integration/targets/nios_vlan/tasks/nios_vlan_idempotence.yml
tests/unit/plugins/modules/test_adminuser.py

- Includes admin user module
- Integration tests for adminuser and vlan

[ADD] nios_adminuser module

---

plugins/lookup/nios_next_vlan_id.py
plugins/modules/nios_vlan.py

- Lookup for next available VLAN ID
- Added example in VLAN module

[ADD] lookup plugin for next_available_vlan_id
