ansible_collections/infoblox/nios_modules/plugins/doc_fragments/nios.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_a_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_aaaa_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_cname_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_dns_view.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_fixed_address.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_host_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_member.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_mx_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_naptr_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_network.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_network_view.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_nsgroup.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_ptr_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_srv_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_txt_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_zone.py
@Vaishnavi-infoblox  I have tried to fix a lot of validate-module failures and added the doc_fragment at the right place
as well as added some missing parameters in spec, whose description you will probably need to add
Can you review and accept the same accordingly
cc: @@felixfontein
=> Fixing validate-modules sanity test failures

ansible_collections/infoblox/nios_modules/plugins/modules/nios_host_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_network.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_network_view.py
@Vaishnavi-infoblox, @anshulbehl Please review the PR
=> Fixed errors for host_record, network and network_view

.github/workflows/ansible-test.yml, ansible_collections/infoblox/nios_modules/CONTRIBUTING.md
Added CONTRIBUTING.md and ansible-test.yml to have CI schedule run
=> Ansible 3.0.0 inclusion

ansible_collections/infoblox/nios_modules/requirements.txt
This PR is a follow up to an email sent to the maintainers of this certified collection notifying them of a few new changes that will be needed for the next Ansible Automation Platform release. Contained in this PR is an example python requirements file built specifically for your collection. You can elect to merge this as is and edit as needed or close the PR and use it as an example to base your own commit off of. if you have any questions about why this PR was sent or confused about its necessity, please don't hesitate to ask in the comments here or email us at ansiblepartners@redhat.com
=> Add requirements.txt file

README.md
This is a simple update to the README.md file, to add references to the newly added DTC modules.
=> Update README.md to add new DTC modules

ansible_collections/infoblox/nios_modules/plugins/module_utils/api.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_fixed_address.py
- Added support to create an IPv6 Fixed address record by passing DUID.
- Bug fixes to update and delete a Fixed address.
=> Bug fixes for fixed address record

ansible_collections/infoblox/nios_modules/plugins/lookup/nios_lookup.py, ansible_collections/infoblox/nios_modules/plugins/module_utils/api.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_a_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_aaaa_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_cname_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_dns_view.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_dtc_lbdn.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_dtc_pool.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_dtc_server.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_fixed_address.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_host_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_member.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_mx_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_naptr_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_network.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_network_view.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_nsgroup.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_ptr_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_restartservices.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_srv_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_txt_record.py, ansible_collections/infoblox/nios_modules/plugins/modules/nios_zone.py
Minor corrections to pass ansible reviewer test.
=> Ansible reviewer corrections

ansible_collections/infoblox/nios_modules/plugins/module_utils/api.py
Fixes: #38 
Originated from:
- https://github.com/ansible-collections/community.general/issues/1786
- https://github.com/ansible-collections/community.general/pull/1788
=> ease limitation for nios_host_record DNS Bypass

README.md, plugins/module_utils/api.py
Fixed module failure error during creation of A-record using next_available_ip.
=> Updated the README links and bug fix

plugins/modules/nios_network.py
Fixes: https://github.com/infobloxopen/infoblox-ansible/issues/25
=> Remove use_option for DHCP option 60

plugins/modules/nios_network.py
Fixes: https://github.com/infobloxopen/infoblox-ansible/issues/61
=> Allow specifying a template when creating a network

plugins/doc_fragments/nios.py, plugins/module_utils/api.py, tests/unit/plugins/module_utils/test_api.py
Changes to run certificate authentication
=> Certificate Based Authentication - Ansible Module

CHANGELOG.rst, README.md, changelogs/.plugin-cache.yaml, changelogs/changelog.yaml, galaxy.yml
Modifying versions and adding release summary
=> Release Notes for v1.4.0

plugins/module_utils/api.py
This PR exists of  one line code change for fixing the update A record issue , when there are multiple IP with same name
=> Fix to update a_record with same name to multiple IP's

CHANGELOG.rst, README.md, changelogs/.plugin-cache.yaml, changelogs/changelog.yaml, galaxy.yml
This is release notes for latest release v1.4.1
=> Release notes for v1.4.1

plugins/module_utils/api.py, plugins/modules/nios_range.py
=> Fixes NIOS Range Update Bugs

plugins/module_utils/api.py, plugins/modules/nios_a_record.py, plugins/modules/nios_aaaa_record.py, plugins/modules/nios_cname_record.py, plugins/modules/nios_dtc_lbdn.py, plugins/modules/nios_dtc_pool.py, plugins/modules/nios_dtc_server.py, plugins/modules/nios_member.py, plugins/modules/nios_mx_record.py, plugins/modules/nios_naptr_record.py, plugins/modules/nios_restartservices.py, plugins/modules/nios_srv_record.py, plugins/modules/nios_txt_record.py, tests/unit/plugins/module_utils/test_api.py, tests/unit/plugins/modules/test_nios_a_record.py, tests/unit/plugins/modules/test_nios_aaaa_record.py, tests/unit/plugins/modules/test_nios_cname_record.py, tests/unit/plugins/modules/test_nios_dns_view.py, tests/unit/plugins/modules/test_nios_host_record.py, tests/unit/plugins/modules/test_nios_mx_record.py, tests/unit/plugins/modules/test_nios_naptr_record.py, tests/unit/plugins/modules/test_nios_network_view.py, tests/unit/plugins/modules/test_nios_nsgroup.py, tests/unit/plugins/modules/test_nios_srv_record.py
- This fix contains the extensible attributes update and delete feature
- Fixes sanity tests failing in devel
=> Fixes Unable update/delete EA's and sanity fix

.github/workflows/ansible-test.yml
This PR contains only updating the workflow simulator version for integration tests.
=> Updating simulator version in integration tests

plugins/modules/nios_a_record.py, plugins/modules/nios_aaaa_record.py, plugins/modules/nios_cname_record.py, plugins/modules/nios_member.py, plugins/modules/nios_mx_record.py, plugins/modules/nios_range.py, plugins/modules/nios_srv_record.py, plugins/modules/nios_txt_record.py
This documentation update is involved with below modules
- A Record
- AAAA Record
- CNAME Record
- Member
- MX Record
- SRV Record
- TXT Record
=> Updates documentation of new parameters added

CHANGELOG.rst, README.md, changelogs/.plugin-cache.yaml, changelogs/changelog.yaml, galaxy.yml
This is PR for  release notes for latest release v1.5.0
=> Release notes for v1.5.0

.github/workflows/ansible-test.yml, tests/integration/targets/nios_a_record/tasks/main.yml, tests/integration/targets/nios_aaaa_record/tasks/main.yml, tests/integration/targets/nios_cname_record/tasks/main.yml, tests/integration/targets/nios_dns_view/tasks/main.yml, tests/integration/targets/nios_host_record/tasks/main.yml, tests/integration/targets/nios_mx_record/tasks/main.yml, tests/integration/targets/nios_naptr_record/tasks/main.yml, tests/integration/targets/nios_network/tasks/main.yml, tests/integration/targets/nios_network_view/tasks/main.yml, tests/integration/targets/nios_ptr_record/tasks/main.yml, tests/integration/targets/nios_srv_record/tasks/main.yml, tests/integration/targets/nios_txt_record/tasks/main.yml, tests/integration/targets/nios_zone/tasks/main.yml, tests/integration/targets/prepare_nios_tests/tasks/main.yml, tests/unit/requirements.txt
* removed unsupported ansible versions 
* added more recent ansible version
* added new required python versions
=> fix: workflow

playbooks/delete_dtc_monitor_sip.yaml, plugins/modules/nios_dtc_monitor_tcp.py
added required param port in example for TCP monitor
=> added required param port in example for TCP monitor

.github/workflows/ansible-test.yml, CHANGELOG.rst, README.md, changelogs/.plugin-cache.yaml, changelogs/changelog.yaml, galaxy.yml, meta/runtime.yml, playbooks/delete_cname_record.yaml, playbooks/delete_dtc_topology.yml, playbooks/delete_mx_record.yaml, playbooks/delete_txt_record.yaml, playbooks/restart_services.yml, playbooks/update_member.yml, tests/requirements.txt, tests/unit/requirements.txt
=> Release notes for v1.6.1

plugins/lookup/nios_next_ip.py
added network_view in get object search.
=> [NPA-79] added network_view in get object search.

plugins/module_utils/api.py, plugins/modules/nios_network.py
Added dhcp options supports for ipv4 and ipv6 network container.
=> - Added dhcp options supports for ipv4 and ipv6 network container.

plugins/module_utils/api.py
- fixed Re-execution of IPv4/v6 network playbook shows 'changed' status.
- fixed configuring DHCP option using 'num' field for network container is failing.
=> - fixed NPA-112 and NPA-114

plugins/module_utils/api.py, plugins/modules/nios_host_record.py
- Updated mac to duid for IPv6Host
- Removed unsupported fields from return_fields
=> Fixed Host record with IPV6
